### ISSUE TITLE
bug:  Objects are colliding upon scrolling (PWA on Windows)

### ISSUE THREAD

**Issue by alex-larkin** [sillsdev/web-languageforge#1151]
**Describe the bug**
When I open an entry in the Chrome PWA for Windows 10 and scroll down, the top paragraph of the entry loses its background, causing text to appear on top of other text and GUI elements. Also, the comment buttons are appearing on top of the Activity Feed button. I have tried reopening the PWA, but the problem persists. 

**To Reproduce**
1. Open an entry using Chrome PWA for Windows 10
2. Scroll down
3. Observe the text on top of other text

**Expected behavior**
When scrolling, the top paragraph should keep a white background, so that the paragraph is easy to read and so that it doesn't collide with other elements of the page. The comments buttons should disappear behind the gray bar on which the Activity Feed button is found. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82162128/132875788-658e6fae-0204-480b-8b13-e2118caddfa8.png)

![image](https://user-images.githubusercontent.com/82162128/132875848-9319bfa2-0271-43e5-92aa-ba700026c153.png)

![delete](https://user-images.githubusercontent.com/82162128/132878972-b169ea04-e809-4b33-b37e-4b4238a9a5ae.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome Version 92.0.4515.159 (Official Build) (64-bit) PWA 

**Mobile (please complete the following information): _problem not observed_**
 - Device: Samsung
 - OS: Android 10
 - Browser Chrome PWA

**Android App in Google Play**
For Mobile, are you using the Language Forge Android app in the Google Play store?  No

**Comment by palmtreefrb** [comment]
This is occurring when focus is on the page and not on the editor. The editors height are slightly taller than the page causing the whole page to scroll up. This will actually be fixed with the [Fix white space on mobile #1143](https://github.com/sillsdev/web-languageforge/pull/1143)

**Comment by rmunn** [comment]
I've noticed that this can be reproduced by clicking on the "Options" dropdown next to the entry filter. If the filter options are hidden, no scrollbar on the page. But if the filter options are visible, there's a second scrollbar on the page, and the page scroll allows the dictionary view (and the top-of-the-page buttons) to overlap, whereas the editor scroll doesn't overlap with the dictionary view.

**Comment by alex-larkin** [comment]
I'm afraid it looks like this issue is back. See video

https://user-images.githubusercontent.com/82162128/142211589-99764198-68b6-44c8-a83a-5b9c28492a2c.mp4

**Comment by megahirt** [comment]
Hi @alex-larkin , this is actually a known issue having to do with the filter options being displayed in the column itself.  We left this as a TODO and closed the issue.  See https://github.com/sillsdev/web-languageforge/issues/1151#issuecomment-921538861 on Sept 17.  The fix probably requires a UI redesign I'm guessing (so the filter options become a modal dialog floating menu)

This issue and the associated PRs are muddy, so I would prefer to still keep track of the issue but create a new issue for it because of the particular circumstances around how we addressed this.
