### ISSUE TITLE
PgUp/PgDn moves two entries at a time instead of one

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1178]
**Describe the bug**
When a user tries to use PgUp/PgDn to navigate entries, an entry is skipped.

**To Reproduce**
1. Go to a word
2. Press PgUp or PgDn
3. Notice the next/previous entry was skipped

**Expected behavior**
PgUp/PgDn should only move backward or forward one entry at a time.

**Screenshots**

https://user-images.githubusercontent.com/4412848/135315994-06b96398-577c-4bcc-97e5-c028fc32afc0.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
This was introduced as part of the work in #1017

**Comment by palmtreefrb** [comment]
This was fixed in #1174 PR

**Comment by megahirt** [comment]
We can't close this issue yet because the PR hasn't been merged - I still have some issues with the open PR.

**Comment by megahirt** [comment]
fixed by #1182 and shipped in 1.9
